#!/usr/bin/env bash
# Add/set the sudoers stuff
groupadd admin

# Back up before making changes
cp /etc/sudoers /etc/sudoers.orig

# Make the sudo group exempt. 
sed -i -e '/Defaults\s\+env_reset/a Defaults\texempt_group=sudo' /etc/sudoers

# Let Admins use no password.
sed -i -e 's/%admin ALL=(ALL) ALL/%admin ALL=NOPASSWD:ALL/g' /etc/sudoers

echo "UseDNS no" >> /etc/ssh/sshd_config